my_string=( "Привет,я строка в нижнем регистре" )
print (len(my_string))
print (("Привет,я строка в нижнем регистре").upper())
print (("Привет,я строка в нижнем регистре").lower())
print (("Привет,я строка в нижнем регистре").replace(' ', ''))
print (my_string[0])
print (my_string[-1])